### PR TITLE
Adjustments to node configuration

### PR DESCRIPTION
**Pull request by atanisoft**
This PR introduces a `Kconfig.projbuild` which contains all user configurable settings that were part of `constants.hxx` previously which fixes https://github.com/atanisoft/esp32olcbhub/issues/10.

Additionally it fixes https://github.com/atanisoft/esp32olcbhub/issues/7 by updating the esp_littlefs dependency with support for multiple file handles pointing to the same file. It is not a perfect solution but it does work as expected, more work will be needed to ensure there is no concurrent file access issues which will be tracked via a new issue.

### CODE REVIEW

**Comment by atanisoft** [comment]
@TrainzLuvr please give this a try and let me know your thoughts. I'm seeing one odd thing after letting it sit for a while:
```
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
[HealthMon 00:33:30] Free heap: 205.50kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 0.38kB
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
[HealthMon 00:34:00] Free heap: 205.32kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 0.38kB
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
```
I'm not certain why there was a ~180b difference in heap yet, but I'll be investigating that further.

**Comment by TrainzLuvr** [comment]
I'll give a try soon.

Now that you mention it, I did notice change in Free heap before, but it was actaully going up after awhile, which to me was bizzare, since the hub was idling.

Unless there's some kind of magic gc happening in the background.

**Comment by atanisoft** [comment]
There will likely be one more LittleFS update before this is merged (more comprehensive fix than what is currently pulled in).

It wouldn't surprise me if there was some sort of GC or other task running that adjusts heap...

**Comment by atanisoft** [comment]
@TrainzLuvr This latest set of commits should fix up most (or all?) of the web issues. I've reworked the code to reconnect the WS if needed before transmitting the requests and moved all but the CDI.xml load over to using the WS. I think this is now ready to review / test and then merge.

**Comment by TrainzLuvr** [comment]
Will give it a whirl, thanks again!

**Comment by TrainzLuvr** [comment]
Hmm, I pulled the latest config branch, built, erase_flash- and flash-ed.

Went to change WiFi TXPower in WebUI and got this in serial monitor:

```
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
Unrecognized request: {"req_type":"cdi-put","offs":133,"size":1,"type":"int","target":"cdi_0_42050261524351473","value":"60"}
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:0,state:Running)
```

It did not save my new value.

**Comment by atanisoft** [comment]
Did you force refresh in the browser? The req_type should be cdi-set with the current html code.

**Comment by TrainzLuvr** [comment]
I erased the index.html.gz, but yeah it seems to be a caching issue on the browser side.

Perhaps you can add no-cache directives in the index.html header?

**Comment by atanisoft** [comment]
I have a tracking issue for the caching directive but haven't gotten it taken care of yet. I'll take a look at getting it fixed and possibly disabling caching entirely for index.html since it is pretty small anyway.

**Pull request merged**
