### PR TITLE
Adjustments for better performance and stability

### PR DESCRIPTION
**Pull request by atanisoft**

### CODE REVIEW

**Comment by atanisoft** [comment]
@TrainzLuvr give this a try. You will need to update the sdkconfig as seen in `sdkconfig.defaults` and update the Esp32WiFiManager.hxx/cpp files from the submodule.

**Comment by TrainzLuvr** [comment]
Alright, been a busy day, going to test this now.

**Comment by TrainzLuvr** [comment]
CAN is no longer working properly:

```
[TWAI] RX:706 (pending:0,overrun:37,discard:0) TX:182 (pending:2,suc:179,fail:1) bus (arb-err:320,err:0,state:Running)
[TWAI] RX:846 (pending:0,overrun:37,discard:0) TX:220 (pending:2,suc:217,fail:1) bus (arb-err:434,err:0,state:Running)
[HealthMon 00:00:30] Free heap: 189.45kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.40kB
[TWAI] RX:846 (pending:0,overrun:37,discard:0) TX:220 (pending:2,suc:217,fail:1) bus (arb-err:434,err:0,state:Running)
```

JRMI Configure Nodes window showed all the nodes at first, then I clicked refresh and they are all gone.

**Comment by TrainzLuvr** [comment]
This still happens:

```
[TWAI] RX:2 (pending:0,overrun:0,discard:0) TX:30 (pending:0,suc:30,fail:0) bus (arb-err:0,err:0,state:Running)
[WiFi] uplink:No (auto:_openlcb-can._tcp,manual::12021) tx:66 sleep:No hub:Yes (_openlcb-can._tcp:12021)
[WiFi] Adjusting maximum WiFi TX power 78 -> 66.
[TWAI] RX:2 (pending:0,overrun:0,discard:0) TX:30 (pending:0,suc:30,fail:0) bus (arb-err:0,err:0,state:Running)
[HealthMon 00:00:30] Free heap: 172.85kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.32kB
[TWAI] RX:2 (pending:0,overrun:0,discard:0) TX:30 (pending:0,suc:30,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:291 (pending:0,overrun:0,discard:0) TX:107 (pending:0,suc:107,fail:0) bus (arb-err:204,err:0,state:Running)
CanDatagramWriteFlow: No datagram response arrived from destination 000000000000.
MemoryConfig: Failed to send response datagram. error code 81000
[TWAI] RX:495 (pending:0,overrun:0,discard:0) TX:173 (pending:0,suc:173,fail:0) bus (arb-err:376,err:0,state:Running)
[HealthMon 00:01:00] Free heap: 172.21kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.32kB
[TWAI] RX:495 (pending:0,overrun:0,discard:0) TX:173 (pending:0,suc:173,fail:0) bus (arb-err:376,err:0,state:Running)
```

I go to CDI for the Hub and it just opens blank.

**Comment by atanisoft** [comment]
If JMRI is not even displaying it's node in the node list when you refresh then it is likely a bug in JMRI itself and not the hub.

Very likely some sort of timer that is expiring just slightly faster than expected.

**Comment by TrainzLuvr** [comment]
Also, it has trouble getting mDNS the first time, then after it finally connects, the connection is dropping :

```
[WiFi] uplink:No (auto:_openlcb-can._tcp,manual::12021) tx:66 sleep:No hub:Yes (_openlcb-can._tcp:12021)
[TWAI] RX:731 (pending:0,overrun:0,discard:0) TX:993 (pending:0,suc:993,fail:0) bus (arb-err:433,err:0,state:Running)
[TWAI] RX:731 (pending:0,overrun:0,discard:0) TX:993 (pending:0,suc:993,fail:0) bus (arb-err:433,err:0,state:Running)
[TWAI] RX:731 (pending:0,overrun:0,discard:0) TX:993 (pending:0,suc:993,fail:0) bus (arb-err:433,err:0,state:Running)
[HealthMon 00:03:30] Free heap: 173.22kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.32kB
[TWAI] RX:731 (pending:0,overrun:0,discard:0) TX:993 (pending:0,suc:993,fail:0) bus (arb-err:433,err:0,state:Running)
[TWAI] RX:731 (pending:0,overrun:0,discard:0) TX:993 (pending:0,suc:993,fail:0) bus (arb-err:433,err:0,state:Running)
[SoftAP aid:1] 40:bd:32:58:e0:e1 connected.
Incoming connection from 192.168.4.2, fd 52.
GCHubPort: Shutting down gridconnect port -1. (0x3ffdc594)
[TWAI] RX:731 (pending:0,overrun:0,discard:0) TX:993 (pending:0,suc:993,fail:0) bus (arb-err:433,err:0,state:Running)
[HealthMon 00:04:00] Free heap: 171.66kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.32kB
Incoming connection from 192.168.4.2, fd 52.
[TWAI] RX:885 (pending:0,overrun:2,discard:0) TX:1213 (pending:0,suc:1213,fail:0) bus (arb-err:491,err:0,state:Running)
GCHubPort: Shutting down gridconnect port -1. (0x3ffdc594)
Incoming connection from 192.168.4.2, fd 52.
[TWAI] RX:1304 (pending:0,overrun:2,discard:0) TX:1475 (pending:0,suc:1475,fail:0) bus (arb-err:578,err:0,state:Running)
[TWAI] RX:2015 (pending:0,overrun:3,discard:0) TX:1850 (pending:0,suc:1850,fail:0) bus (arb-err:781,err:0,state:Running)
[HealthMon 00:04:30] Free heap: 168.70kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.20kB
[TWAI] RX:2337 (pending:0,overrun:5,discard:0) TX:1983 (pending:0,suc:1983,fail:0) bus (arb-err:839,err:0,state:Running)
[TWAI] RX:2485 (pending:0,overrun:8,discard:0) TX:2079 (pending:0,suc:2079,fail:0) bus (arb-err:892,err:0,state:Running)
[TWAI] RX:2674 (pending:0,overrun:8,discard:0) TX:2153 (pending:0,suc:2153,fail:0) bus (arb-err:921,err:0,state:Running)
[HealthMon 00:05:00] Free heap: 168.48kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.20kB
[TWAI] RX:2674 (pending:0,overrun:8,discard:0) TX:2153 (pending:0,suc:2153,fail:0) bus (arb-err:921,err:0,state:Running)
```

There's also noticable lag at first when trying to switch locomotives (I got two in the TrainDb). It seems to be working but it feels "shaky" and those **arb-err** keep climbing up.

**Comment by atanisoft** [comment]
I've seen the connection issues as well and not 100% certain of the cause. I added a debug line locally to print out why the disconnect was logged and often it was "connection reset by peer".

> It seems to be working but it feels "shaky" and those **arb-err** keep climbing up.

Ok, the arb-err increases is a concern but normally the packets will be re-transmitted so I'm not 100% certain it is a major concern. It will need some further investigation for sure.

**Comment by TrainzLuvr** [comment]
This is current state:

```
[TWAI] RX:4476 (pending:0,overrun:143,discard:0) TX:6055 (pending:0,suc:6055,fail:0) bus (arb-err:1139,err:0,state:Running)
[HealthMon 00:15:00] Free heap: 168.20kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.66kB
```

Those RX overruns have climbed up. Are the arb-err some kind of a feedback/retry?

WiFi/LCC connection does appear more stable, as I was able to pull the CDI off of UWT-100 without it dropping.

**Comment by atanisoft** [comment]
The overruns don't look too bad considering, but definitely will need to keep an eye on them and see about maybe increasing the CAN RX buffer size by adding this snippet to esp32olcbhub.cpp (near the other similar ones):
```
OVERRIDE_CONST(can_rx_buffer_size, 32);
```
The default buffer size is 16 frames. We just need to be careful with how high it is set since it will increase heap usage.

> Are the arb-err some kind of a feedback/retry?

Arbitration errors while trying to talk to the bus. These usually result in a retransmit of the frame I believe.

**Comment by TrainzLuvr** [comment]
There's plenty of heap it seems so increasing the RX buffer size shouldn't affect it that much, no?

After all what are we saving the heap for? :)

**Comment by atanisoft** [comment]
> After all what are we saving the heap for? :)

WiFi/TCP RX/TX buffers... 

I'd say increase the can_rx_buffer_size to 32 or possibly 48 if there are still frames being dropped.

**Comment by TrainzLuvr** [comment]
I just did to 32, but now throttle is having problems connecting, doesn't find mDNS, or maybe WiFi isn't connected either.

If I connect from my computer with curl I can see that connection in the serial monitor right away, yet I don't see throttle's connections coming up at all.

**Comment by TrainzLuvr** [comment]
I don't think rx_buffer_size did much...I rebooted the throttle:

```
[SoftAP aid:1] 40:bd:32:58:e0:e1 connected.
[SoftAP aid:1] 40:bd:32:58:e0:e1 disconnected.
[SoftAP aid:1] 40:bd:32:58:e0:e1 connected.
Incoming connection from 192.168.4.2, fd 51.
[TWAI] RX:2 (pending:0,overrun:0,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:2 (pending:0,overrun:0,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:2 (pending:32,overrun:36,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:2 (pending:32,overrun:36,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:2 (pending:32,overrun:36,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:2 (pending:32,overrun:36,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
[TWAI] RX:2 (pending:32,overrun:36,discard:0) TX:31 (pending:0,suc:31,fail:0) bus (arb-err:0,err:0,state:Running)
```
Flakey throttle too... :)

**Comment by TrainzLuvr** [comment]
After rebooting the throttle it finally connects.

I notice a lag from when I issue the command till the locomotive actually reacts.

Sometimes it's imperceptable, but other times there's hesitation. IDK if the Hub is not passing these out fast enough (emptying buffers) or something else between the throttle and the Hub, or the Hub and the CS.

Then after running for a bit, it seems to just drop (something drops - either the throttle or the Hub). Throttle stops responding and freezes then I get that "Failed to select loco (code 80000): Failed to assign train" message on the throttle.

And the overrun's start going up, about the same time the throttle froze:

```
[TWAI] RX:166 (pending:0,overrun:0,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:0,overrun:0,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
[TWAI] RX:166 (pending:32,overrun:36,discard:0) TX:328 (pending:0,suc:328,fail:0) bus (arb-err:29,err:0,state:Running)
```

**Comment by TrainzLuvr** [comment]
I've also lost the Hub in the nodes window in JMRI, and overrun is now up to 240, from 36, just like that.

**Comment by atanisoft** [comment]
@TrainzLuvr I've pushed one small update to the `sdkconfig.defaults` file which should fix the mDNS issue. The default priority is too low compared to the OpenMRN tasks so it ends up waiting for a while to execute.

**Comment by TrainzLuvr** [comment]
I did some config changes myself in sdkconfig and found these to be ok:
```
CONFIG_LWIP_TCP_MSS=1460
CONFIG_LWIP_TCP_SND_BUF_DEFAULT=8760
CONFIG_LWIP_TCP_WND_DEFAULT=29200
CONFIG_LWIP_TCP_RECVMBOX_SIZE=22
```
I tried all kinds of values but increasing some did not make much difference on the overall.

And in esp32olcbhub.cpp:
```
OVERRIDE_CONST_DEFERRED(gridconnect_buffer_size, CONFIG_LWIP_TCP_MSS);
OVERRIDE_CONST(can_rx_buffer_size, 48);
```

Those overruns in RX happen when I click Refresh in the Configure Nodes JMRI window a few times consecutively.

I also noticed that TX side ends up having a few pending packets but they never get cleared, they are just stuck there until I reset the node. On the RX pending packets end up clearing on their own, so not sure what's going on?

Arb-err is pretty annoying too because it never goes away and I think it was not happening on my ESP32CS_barebone branch, iirc.

**Comment by atanisoft** [comment]
Ok, I'll pull in the updates you have above for sdkconfig and bump the rx buffer size. The grid connect buffer size probably doesn't make a big difference overall since it is capped at two frames max anyway so it doesn't overload the TCP stack.

As for the TX pending, that is a cosmetic bug where a tracking car is not being updated with locks. I'll see if I can find a simple way to do that.

**Comment by TrainzLuvr** [comment]
My values were based on the ESP32 docs, MSS, SND_BUF, WND_DEFAULT and TCP_RECVMBOX, so I tried above and below these ones.

By the way, I noticed that lowering the can_rx_buffer_size to 16 causes that LoadProhibited crash.

I also tried setting can_tx_buffer_size to 32 or 48 but I did not notice any improvement in the TX side of the TWAI log.

**Comment by atanisoft** [comment]
Interesting find on the RX side, perhaps a base value of 32 then and for hub we bump to 48. The CS uses 128 and I'll be lowering that to 48 once I sync changes over.

The TX queue size is not as critical as it will drain very quickly and not impact the log statement much (or at all). There is likely a missing TX decrement in a certain flow so I'll step through the flows and fix that soon 

Which docs did you reference for the parameters so I can add comments to link to them in the config. Any impacts on free heap from bumping the sizes?

**Comment by TrainzLuvr** [comment]
Their API reference, the suggested values for MSS and multiplications of it for SND, at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-lwip-tcp-mss

Also, I noticed that at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-lwip-tcpip-recvmbox-size they say that TCPIP_RECVMBOX_SIZE should be larger than TCP_RECVMBOX_SIZE, so I left the former at 64 but lowered the latter to be as they suggest LWIP_WND_DEFAULT_SIZE/LWIP_TCP_MSS + 2 and since I opted for 20*MSS for WND, RECVMBOX ended up being 22. :)

**Comment by TrainzLuvr** [comment]
The free heap actually shows higher than before, I don't understand that part. And I mean, after making some of these values much higher, the free heap kept above 180 KB despite all that.

**Comment by atanisoft** [comment]
Ok good to know. I'll update this in a bit and do some more testing as well.

**Comment by atanisoft** [comment]
Heap may be staying higher as it has larger buffers and not needing to allocate as many smaller ones.

**Comment by atanisoft** [comment]
Also regarding TX and RX can buffer sizes... The old code uses 24 (effective) since it allocated 8 frames on the IDF side and 16 on OpenMRN side. The new code only allocates the OpenMRN side since they are merged as one now. So the higher RX setting makes sense somewhat. I'll add a platform check and bump to 32 base for esp32

**Comment by TrainzLuvr** [comment]
Do you have any ideas about preventing those overruns, because we've both done only limited testing.

I'm thinking, during an OPS for example that lasts 3-4 hours, the number of packets going through the Hub would surely overflow something, and cause a crash, no?

There just seems to be some kind of a disconnect between filling and emptying buffers, on both RX and TX side.

**Comment by atanisoft** [comment]
The overruns are due to very high traffic volume, often cdi elements. The CS will serve up both CDI and FDI for each train and the UWT-100 will download both. It likely will cache both though.

So some testing in acquire /release of loco would be good. Especially if we can get two or three UWT-100 on the bus. We may need to simulate a few throttles via command line tools.

**Comment by atanisoft** [comment]
Keep in mind there is no locking on the stats counters in the TWAI driver and that will contribute to periodic misprints. The reads are fine but writes need protection, I'll need to look at adding something for that as long as it does not slow it down much. Acceptable can rate is 900-1250 frames per second and from my load testing I was seeing around +/- 910/sec, it may be better now with some of the recent tweaks (will test).

**Comment by TrainzLuvr** [comment]
When you say "acceptable frame rate" is that what OpenMRN spec is, or what ESP32 can tolerate before it explodes? :)

**Comment by atanisoft** [comment]
Maximum throughput range at 125kbps data rate.

**Comment by atanisoft** [comment]
CAN load test output:
```
[TWAI] RX:3645 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:12837 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:22028 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:18,state:Running)
[HealthMon 00:00:30] Free heap: 199.65kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 0.52kB
[TWAI] RX:31220 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:34463 (pending:0,overrun:0,discard:0) TX:12 (pending:0,suc:12,fail:0) bus (arb-err:0,err:18,state:Running)
```
Send rate of 1250/sec (max possible speed). Approximately 919/sec processed with zero overruns. Slight performance boost over previous test.

TCP/IP GC load test output:
```
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:2733 (pending:0,suc:2733,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:9809 (pending:0,suc:9809,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:16884 (pending:2,suc:16882,fail:0) bus (arb-err:0,err:18,state:Running)
[HealthMon 00:00:30] Free heap: 171.93kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.57kB
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:23964 (pending:0,suc:23964,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:31052 (pending:3,suc:31049,fail:0) bus (arb-err:0,err:18,state:Running)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:38106 (pending:2,suc:38104,fail:0) bus (arb-err:0,err:18,state:Running)
[HealthMon 00:01:00] Free heap: 171.01kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.57kB
```
Approximately 707/sec, so a bit slower throughput but it is bridging from TCP/IP -> CAN. This may be around top end.

**Pull request merged**
