### PR TITLE
Move to MemoryConfigClient for CDI get/set

### PR DESCRIPTION
**Pull request by atanisoft**
:tractor: Move CDI get/set to MemoryConfigClient
:ambulance: Fix Factory Reset from web so it actually does that.

fixes: https://github.com/atanisoft/esp32olcbhub/issues/15

### CODE REVIEW

**Comment by atanisoft** [comment]
@TrainzLuvr Give this a try and let me know your thoughts. There are submodule updates and hopefully a fix to refresh the gzip files during build if they are stale.

**Comment by TrainzLuvr** [comment]
I just noticed that the branch is now config2.

So, this means we don't need to erase any .gz files by hand anymore?

Are there any changes in sdkconfig, can I use the one from config branch?

**Comment by atanisoft** [comment]
> I just noticed that the branch is now config2.

Yup, merged the previous branch to "main" (they renamed master -> main recently...)

> So, this means we don't need to erase any .gz files by hand anymore?

Hopefully. I may need to tweak the CMakeLists.txt further but hopefully this works.

> can I use the one from my config branch?

Reuse is fine.

**Comment by atanisoft** [comment]
@TrainzLuvr Give the latest a try, including the Hub mode. I can't get it to drop CAN frames now (loading a 14kb CDI and multiple refresh of JMRI node list, no drops!)

**Comment by TrainzLuvr** [comment]
hmm, well I don't know...

```
[TWAI] RX:31 (pending:0,overrun:0,discard:0) TX:71 (pending:1,suc:70,fail:0) bus (arb-err:0,err:0,state:Running)
[HealthMon 00:02:00] Free heap: 162.56kB (max block size: 106.41kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.77kB
[TWAI] RX:328 (pending:0,overrun:56,discard:0) TX:72 (pending:1,suc:71,fail:0) bus (arb-err:0,err:0,state:Running)
CanDatagramWriteFlow: No datagram response arrived from destination 000000000000.
MemoryConfig: Failed to send response datagram. error code 81000
[TWAI] RX:394 (pending:0,overrun:56,discard:0) TX:100 (pending:1,suc:99,fail:0) bus (arb-err:33,err:0,state:Running)
[TWAI] RX:394 (pending:0,overrun:56,discard:0) TX:100 (pending:1,suc:99,fail:0) bus (arb-err:33,err:0,state:Running)
[HealthMon 00:02:30] Free heap: 147.34kB (max block size: 101.39kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 1.77kB
[TWAI] RX:394 (pending:0,overrun:56,discard:0) TX:100 (pending:1,suc:99,fail:0) bus (arb-err:33,err:0,state:Running)
[TWAI] RX:394 (pending:0,overrun:56,discard:0) TX:100 (pending:1,suc:99,fail:0) bus (arb-err:33,err:0,state:Running)
```

The CDI window is just haging, empty no text in it...waiting for something. Wouldn't close either right away, had to click a few times and wait.

Also this from JRMI Traffic Monitor

```
17:11:53.755: [[1a849d6e] 20 01 00 00 00 BF 00   ]  S: 02.01.12.7F.22.48 - 05.02.01.03.00.00 Datagram: (7) 20.1.0.0.0.BF.0
17:11:55.517: [[19a28849] 0D 6E 80               ]  R: 05.02.01.03.00.00 - 02.01.12.7F.22.48 DatagramReceivedOK with payload 80
  Src: ESP32OlcbHub
17:11:55.518: [[1ad6e849] 20 11 00 00 00 BF      ]  R: 05.02.01.03.00.00 - 02.01.12.7F.22.48 Datagram: (6) 20.11.0.0.0.BF
  Src: ESP32OlcbHub
17:11:55.525: [[19a28d6e] 08 49                  ]  S: 02.01.12.7F.22.48 - 05.02.01.03.00.00 DatagramReceivedOK with no payload
17:11:55.715: [[1a849d6e] 20 A8                  ]  S: 02.01.12.7F.22.48 - 05.02.01.03.00.00 Datagram: (2) 20.A8
17:11:55.721: [[19a28849] 0D 6E 00               ]  R: 05.02.01.03.00.00 - 02.01.12.7F.22.48 DatagramReceivedOK with no payload
  Src: ESP32OlcbHub
17:11:56.741: [[1a849d6e] 20 A9                  ]  S: 02.01.12.7F.22.48 - 05.02.01.03.00.00 Datagram: (2) 20.A9
17:11:56.747: [[19a48849] 0D 6E 10 41            ]  R: 05.02.01.03.00.00 - 02.01.12.7F.22.48 DatagramRejected with payload 10 41
```
I was updating a config value through CDI, and did More...->Update Complete, and More...->Reboot, so the above is just before it rebooted.

**Comment by atanisoft** [comment]
> The CDI window is just haging, empty no text in it...waiting for something. Wouldn't close either right away, had to click a few times and wait.

I suspect that is more of a bug in the JMRI side than the esp32 side. There seems to be some instability in the OpenLCB code in JMRI that has not been fixed yet.

**Comment by TrainzLuvr** [comment]
Was wondering, does that WiFi Power Savings Mode option need to be exposed?

I doubt anyone would use it (battery power?) and if they turn it on by accident would only cause headaches.

Otherwise, I don't see anything else.

**Comment by atanisoft** [comment]
> does that WiFi Power Savings Mode option need to be exposed?

It should be probably buried in a nested group for "advanced" settings (along with the TX power setting)

**Comment by TrainzLuvr** [comment]
Just something to consider, not sure if there are any other options that are needed?

**Pull request merged**
